=== 1028176322-dot/wegame/data/schemas/damage_armor_matrix.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "damage_armor_matrix",
  "type": "object",
  "properties": {
    "control_air": {
      "type": "number"
    },
    "control_heavy": {
      "type": "number"
    },
    "control_light": {
      "type": "number"
    },
    "control_magic_immune": {
      "type": "number"
    },
    "control_none": {
      "type": "number"
    },
    "magic_air": {
      "type": "number"
    },
    "magic_heavy": {
      "type": "number"
    },
    "magic_light": {
      "type": "number"
    },
    "magic_magic_immune": {
      "type": "number"
    },
    "magic_none": {
      "type": "number"
    },
    "physical_air": {
      "type": "number"
    },
    "physical_heavy": {
      "type": "number"
    },
    "physical_light": {
      "type": "number"
    },
    "physical_magic_immune": {
      "type": "number"
    },
    "physical_none": {
      "type": "number"
    },
    "poison_air": {
      "type": "number"
    },
    "poison_heavy": {
      "type": "number"
    },
    "poison_light": {
      "type": "number"
    },
    "poison_magic_immune": {
      "type": "number"
    },
    "poison_none": {
      "type": "number"
    }
  },
  "required": [],
  "additionalProperties": false
}

=== 1028176322-dot/wegame/data/config/damage_armor_matrix.json
{
  "physical_none": 1.0,
  "physical_light": 1.5,
  "physical_heavy": 1.5,
  "physical_magic_immune": 1.5,
  "physical_air": 0.5,
  "magic_none": 1.0,
  "magic_light": 1.0,
  "magic_heavy": 1.0,
  "magic_magic_immune": 0.0,
  "magic_air": 0.5,
  "poison_none": 1.0,
  "poison_light": 1.0,
  "poison_heavy": 1.5,
  "poison_magic_immune": 1.0,
  "poison_air": 0.5,
  "control_none": 1.0,
  "control_light": 1.0,
  "control_heavy": 1.0,
  "control_magic_immune": 1.0,
  "control_air": 1.0
}
