=== 1028176322-dot/wegame/data/schemas/unlock_config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "unlock_config",
  "type": "object",
  "properties": {
    "electric_required_level": {
      "type": "number"
    },
    "gold_effect_value": {
      "type": "number"
    },
    "gold_required_level": {
      "type": "number"
    },
    "leaderboard_required_level": {
      "type": "number"
    },
    "levels_required_level": {
      "type": "number"
    },
    "lives_effect_value": {
      "type": "number"
    },
    "lives_required_level": {
      "type": "number"
    },
    "magic_required_level": {
      "type": "number"
    },
    "poison_required_level": {
      "type": "number"
    },
    "wood_effect_value": {
      "type": "number"
    },
    "wood_required_level": {
      "type": "number"
    }
  },
  "required": [],
  "additionalProperties": false
}

=== 1028176322-dot/wegame/data/config/unlock_config.json
{
  "magic_required_level": 3.0,
  "poison_required_level": 6.0,
  "electric_required_level": 10.0,
  "gold_required_level": 2.0,
  "lives_required_level": 4.0,
  "wood_required_level": 8.0,
  "leaderboard_required_level": 12.0,
  "levels_required_level": 5.0,
  "gold_effect_value": 20.0,
  "lives_effect_value": 2.0,
  "wood_effect_value": 20.0
}
